update minified files

diff --git a/.github/workflows/minify.yml b/.github/workflows/minify.yml
--- a/.github/workflows/minify.yml
+++ b/.github/workflows/minify.yml
@@ -57,7 +57,12 @@ jobs:
           echo "Minifying files and appending version suffix..."
           npx html-minifier-terser index.html -o minified/index.min.${NEW_VERSION}.html --collapse-whitespace --remove-comments --minify-css true --minify-js true
           npx terser badge.js -o minified/badge.min.${NEW_VERSION}.js --compress --mangle --ecma 2020 --toplevel --output beautify=false
-          cp minified/badge.min.${NEW_VERSION}.js minified/badge.min.js
+          if [ -f "minified/badge.min.${NEW_VERSION}.js" ]; then
+            cp minified/badge.min.${NEW_VERSION}.js minified/badge.min.js
+          else
+            echo "Error: Minified badge.js not found!" >&2
+            exit 1
+          fi
 
       - name: Commit and Push Minified Files
         run: |
